### ISSUE TITLE
Evaluation Metric

### ISSUE THREAD

**Issue by krantiparida** [SheldonTsui/PseudoBinaural_CVPR2021#6]
Hi, I have some confusion about the evaluation metric used for the paper.
1. is STFT and ENV reported in the paper is obtained by the function [STFT_L2_distance](https://github.com/SheldonTsui/PseudoBinaural_CVPR2021/blob/d88f30a7d580e227f8aa9ae1b8f866c71ca35044/evaluate.py#L52) and [Envelope_distance](https://github.com/SheldonTsui/PseudoBinaural_CVPR2021/blob/d88f30a7d580e227f8aa9ae1b8f866c71ca35044/evaluate.py#L75)? If so both STFT and ENV has different metric, wherein STFT squared L2 distance is used and for ENV direct L2 distance is used? is it done following the prior works?
2. Can you please point to the function that computes Mag as reported in evaluation tables? There are a bunch of MSE calculation functions and I am confused which one was particularly used for the calculation.
3. For the phase error calculation, in the paper it is mentioned that L2 loss is used for calculation but from the [code](https://github.com/SheldonTsui/PseudoBinaural_CVPR2021/blob/d88f30a7d580e227f8aa9ae1b8f866c71ca35044/evaluate.py#L142), it seems L1 loss is used? Could you please clarify what did you use? Also for phase error calculation, there is some [clipping](https://github.com/SheldonTsui/PseudoBinaural_CVPR2021/blob/d88f30a7d580e227f8aa9ae1b8f866c71ca35044/evaluate.py#L143) performed with the values. It would be really helpful if you could explain the rationale behind it.

Thanks.

**Comment by SheldonTsui** [comment]
Hi, @krantiparida I'm sorry about the previous messy evaluation protocols. I have cleaned the metrics and update them in the latest push.
1. In our code, `STFT_L2_distance' and `Envelope_distance' are both following the prior works. Here, I have to mention **_the normalization bug_** in previous implementations as presented in Appendices C of our paper. 
2. I have updated the code and please refer to the Mag distance.
3. Note that we use angle values to represent the phase distance. But note that, the angular distance between gt and prediction will be never bigger than \pi(the audiences care more about sensing the source directions). Therefore, we use a clipping operation to meet this constraint.

**Comment by SheldonTsui** [comment]
Hi, @krantiparida I'm sorry about the previous messy evaluation protocols. I have cleaned the metrics and update them in the latest push.
1. In our code, `STFT_L2_distance` and `Envelope_distance` are both following the prior works. Here, I have to mention **_the normalization bug_** in previous implementations as presented in Appendices C of our paper. 
2. I have updated the code and please refer to the Mag distance.
3. In the paper, we use angle values to represent the phase distance. But note that, the angular distance between GT and prediction will be never bigger than \pi(the audiences care more about sensing the source directions). Therefore, we use a clipping operation to meet this constraint.

**Comment by krantiparida** [comment]
Thanks, @SheldonTsui for the response and update in the code. It is much clear now. 
I still do not get how the implementation is equivalent to L2 loss for the phase error (as mentioned in the paper), it seems L1 loss is calculated between both as it is using np.abs(). Could you please clarify? 
Thanks.

**Comment by SheldonTsui** [comment]
Hi, @krantiparida. We use angle values to represent the phase and the angles in the spectrogram are independent. For an individual angle value, the distance between GT and prediction is exactly the absolute value of their difference. Hence, 1-norm or 2-norm here is not that important. For simplicity, we just write 2-norm here. _However, I agree that using the 1-norm here will be better and not lead to confusion._

**Comment by krantiparida** [comment]
Thanks for the clarification @SheldonTsui.
